# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
changelog:
  skip: true
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE-MIT
    rlcp: true
nfpms:
  - vendor: pomdtr
    homepage: https://github.com/pomdtr/{{ .ProjectName }}
    maintainer: Achille Lacoin
    description: Generate powerful UIs from simple scripts written in any language.
    license: MIT
    formats:
      - apk
      - deb
      - rpm
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
brews:
  - name: "{{ .ProjectName }}"
    homepage: https://github.com/pomdtr/{{ .ProjectName }}
    tap:
      owner: pomdtr
      name: homebrew-tap
    install: |-
      bin.install "{{ .ProjectName }}"
