name: Publish Release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-msvc
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: |
          deno compile \
            --allow-all \
            --target ${{ matrix.target }} \
            ./vt.ts
      - name: Create Archive
        id: archive
        run: |
          ARCHIVE_NAME=name=vt-${GITHUB_REF_NAME#v}-x86_64-unknown-linux-gnu
          if [[ ${{ matrix.target }} == 'x86_64-pc-windows-msvc' ]]; then
            zip "${ARCHIVE_NAME}.zip" vt.exe LICENSE README.md
            echo "${ARCHIVE_NAME}.zip" >> "$GITHUB_OUTPUT"
          else
            tar zcvf "${ARCHIVE_NAME}.tar.gz" vt LICENSE README.md
            echo "name=${ARCHIVE_NAME}.tar.gz" >> $GITHUB_OUTPUT
          fi

      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: ${{steps.archive.outputs.name}}
  publish:
    needs: [compile]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: output
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            output/*
