name: Publish Release
on:
  push:
    # tags:
    #   - "v*"
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-msvc
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Write release version
        id: version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "res=$VERSION" >> $GITHUB_OUTPUT
      - run: |
          deno compile \
            --target ${{ matrix.target }} \
            --output ./vt-${{steps.version.outputs.res}}-${{matrix.target}} \
            ./vt.ts
