name: Publish Release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-msvc
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: extract version
        id: extract-version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "name=$VERSION" >> $GITHUB_OUTPUT
      - run: |
          deno compile \
            --target ${{ matrix.target }} \
            ./vt.ts
      - run: |
          OUTPUT=vt-${{steps.extract-version.outputs.name}}-${{matrix.target}}.tar.gz
          tar zcvf "$OUTPUT" vt LICENSE README.md
          echo "OUTPUT=$OUTPUT" >> $GITHUB_ENV
        if: matrix.target != 'x86_64-pc-windows-msvc'
      - run: |
          OUTPUT=vt-${{steps.extract-version.outputs.name}}-${{matrix.target}}.zip
          zip "$OUTPUT" vt.exe LICENSE README.md
          echo "OUTPUT=$OUTPUT" >> $GITHUB_ENV
        if: matrix.target == 'x86_64-pc-windows-msvc'
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: ${{github.env.OUTPUT}}
  publish:
    needs: [compile]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: output
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            output/*
