name: Publish Release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-msvc
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: write binary name
        id: binary
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "name=./vt-$VERSION-${{matrix.target}}${{matrix.target == 'x86_64-pc-windows-msvc' && '.exe'}}" >> $GITHUB_OUTPUT
      - run: |
          deno compile \
            --target ${{ matrix.target }} \
            --output ${{steps.binary.outputs.name}} \
            ./vt.ts
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: ${{steps.binary.outputs.name}}
  publish:
    needs: [compile]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: bin
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/*
